aem-authoring-toolkit-assets/src/main/content/jcr_root/apps/authoring-toolkit/depends-on/README.md
aem-authoring-toolkit-assets/src/main/content/jcr_root/apps/authoring-toolkit/depends-on/js/dependsOnElementAccessors.js
aem-authoring-toolkit-assets/src/main/content/jcr_root/apps/authoring-toolkit/depends-on/js/dependsOnObserver.js

bugfix:
- hidden field wrapper element is excluded from validation

[DependsOn 1.1.0]:

---

aem-authoring-toolkit-assets/src/main/content/jcr_root/apps/authoring-toolkit/depends-on/README.md
aem-authoring-toolkit-assets/src/main/content/jcr_root/apps/authoring-toolkit/depends-on/js/accessors/dependsOnCoralRTEAccessor.js
aem-authoring-toolkit-assets/src/main/content/jcr_root/apps/authoring-toolkit/depends-on/js/dependsOnElementAccessors.js

- fix bug with default required state accessor (not handled properly by foundation-validation)

[DependsOn] updated to 1.2.0

---

aem-authoring-toolkit-api/src/main/java/com/exadel/aem/toolkit/api/annotations/assets/dependson/DependsOnActions.java
aem-authoring-toolkit-assets/src/main/content/jcr_root/apps/authoring-toolkit/depends-on/README.md
aem-authoring-toolkit-assets/src/main/content/jcr_root/apps/authoring-toolkit/depends-on/css.txt
aem-authoring-toolkit-assets/src/main/content/jcr_root/apps/authoring-toolkit/depends-on/css/dependsOnDisabled.less
aem-authoring-toolkit-assets/src/main/content/jcr_root/apps/authoring-toolkit/depends-on/css/dependsOnValidate.less
aem-authoring-toolkit-assets/src/main/content/jcr_root/apps/authoring-toolkit/depends-on/js/accessors/dependsOnCQFileUploadAccessor.js
aem-authoring-toolkit-assets/src/main/content/jcr_root/apps/authoring-toolkit/depends-on/js/accessors/dependsOnCoralRTEAccessor.js
aem-authoring-toolkit-assets/src/main/content/jcr_root/apps/authoring-toolkit/depends-on/js/actions/dependsOnCoralBasicActions.js
aem-authoring-toolkit-assets/src/main/content/jcr_root/apps/authoring-toolkit/depends-on/js/dependsOnElementAccessors.js

Added default, rte, fileUpload disable accessor and disabled action

DependsOn 1.3.0: Disabled accessor/action

---

aem-authoring-toolkit-assets/src/main/content/jcr_root/apps/authoring-toolkit/depends-on/README.md
aem-authoring-toolkit-assets/src/main/content/jcr_root/apps/authoring-toolkit/depends-on/js/accessors/dependsOnCoralSwitcherAccessors.js
aem-authoring-toolkit-assets/src/main/content/jcr_root/apps/authoring-toolkit/depends-on/js/actions/dependsOnCoralBasicActions.js
aem-authoring-toolkit-assets/src/main/content/jcr_root/apps/authoring-toolkit/depends-on/js/dependsOnElementAccessors.js

- fix bug with set action chain

DependsOn: 1.3.1 bugfix

---

README.md
aem-authoring-toolkit-api/src/main/java/com/exadel/aem/toolkit/api/annotations/assets/dependson/DependsOn.java
aem-authoring-toolkit-api/src/main/java/com/exadel/aem/toolkit/api/annotations/assets/dependson/DependsOnActions.java
aem-authoring-toolkit-api/src/main/java/com/exadel/aem/toolkit/api/annotations/assets/dependson/DependsOnParam.java
aem-authoring-toolkit-assets/src/main/content/jcr_root/apps/authoring-toolkit/depends-on/README.md
aem-authoring-toolkit-assets/src/main/content/jcr_root/apps/authoring-toolkit/depends-on/css/dependsOnDisabled.less
aem-authoring-toolkit-assets/src/main/content/jcr_root/apps/authoring-toolkit/depends-on/css/dependsOnValidate.less
aem-authoring-toolkit-assets/src/main/content/jcr_root/apps/authoring-toolkit/depends-on/js.txt
aem-authoring-toolkit-assets/src/main/content/jcr_root/apps/authoring-toolkit/depends-on/js/accessors/dependsOnCoralRTEAccessor.js
aem-authoring-toolkit-assets/src/main/content/jcr_root/apps/authoring-toolkit/depends-on/js/accessors/dependsOnCoralSwitcherAccessors.js
aem-authoring-toolkit-assets/src/main/content/jcr_root/apps/authoring-toolkit/depends-on/js/actions/dependsOnCoralBasicActions.js
aem-authoring-toolkit-assets/src/main/content/jcr_root/apps/authoring-toolkit/depends-on/js/actions/dependsOnCoralValidateAction.js
aem-authoring-toolkit-assets/src/main/content/jcr_root/apps/authoring-toolkit/depends-on/js/dependsOn.js
aem-authoring-toolkit-assets/src/main/content/jcr_root/apps/authoring-toolkit/depends-on/js/dependsOnActionRegistry.js
aem-authoring-toolkit-assets/src/main/content/jcr_root/apps/authoring-toolkit/depends-on/js/dependsOnElementAccessors.js
aem-authoring-toolkit-assets/src/main/content/jcr_root/apps/authoring-toolkit/depends-on/js/dependsOnObserver.js
aem-authoring-toolkit-assets/src/main/content/jcr_root/apps/authoring-toolkit/depends-on/js/dependsOnQueryObserver.js
aem-authoring-toolkit-assets/src/main/content/jcr_root/apps/authoring-toolkit/depends-on/js/dependsOnQueryProcessor.js
aem-authoring-toolkit-assets/src/main/content/jcr_root/apps/authoring-toolkit/depends-on/js/dependsOnUtils.js
aem-authoring-toolkit-assets/src/main/content/jcr_root/apps/authoring-toolkit/depends-on/js/references/dependsOnElementReference.js
aem-authoring-toolkit-assets/src/main/content/jcr_root/apps/authoring-toolkit/depends-on/js/references/dependsOnGroupReference.js
aem-authoring-toolkit-assets/src/main/content/jcr_root/apps/authoring-toolkit/depends-on/js/references/dependsOnObservedReference.js
aem-authoring-toolkit-plugin/src/main/java/com/exadel/aem/toolkit/core/handlers/assets/dependson/DependsOnHandler.java

- build in action params
- observer instances
- readonly action
- WIP: multiple validate action
- bugfixes

DependsOn v2.1.0

---

aem-authoring-toolkit-assets/src/main/content/jcr_root/apps/authoring-toolkit/depends-on/js/actions/dependsOnCoralValidateAction.js

Strict mode to force update validity after initial update.

DependsOn: validate action strict mode

---

aem-authoring-toolkit-assets/src/main/content/jcr_root/apps/authoring-toolkit/depends-on/js/actions/dependsOnCoralValidateAction.js
aem-authoring-toolkit-assets/src/main/content/jcr_root/apps/authoring-toolkit/depends-on/js/dependsOn.js
aem-authoring-toolkit-assets/src/main/content/jcr_root/apps/authoring-toolkit/depends-on/js/dependsOnQueryObserver.js
aem-authoring-toolkit-assets/src/main/content/jcr_root/apps/authoring-toolkit/depends-on/js/references/dependsOnElementReference.js

Renamed DependsOnQueryObserver to QueryObserver and fixed `this` reference undefined data-dependsonref attribute

[DependsOn] Fix for 'this' reference

---

aem-authoring-toolkit-assets/pom.xml
pom.xml

profile name is install-assets

[EDMTP-191] Added maven profile for automatic installation of AAT-assets

---

aem-authoring-toolkit-assets/src/main/content/jcr_root/apps/authoring-toolkit/depends-on/README.md
aem-authoring-toolkit-assets/src/main/content/jcr_root/apps/authoring-toolkit/depends-on/js/dependsOnActionRegistry.js

https://github.com/exadel-inc/aem-authoring-toolkit/pull/71
The same PR for 1.2.1 release

[DependsOn] [Release 1.2.1] Action's registry. Names pattern

---

aem-authoring-toolkit-api/src/main/java/com/exadel/aem/toolkit/api/annotations/assets/dependson/DependsOnRef.java
aem-authoring-toolkit-assets/src/main/content/jcr_root/apps/authoring-toolkit/depends-on/README.md
aem-authoring-toolkit-assets/src/main/content/jcr_root/apps/authoring-toolkit/depends-on/js/dependsOn.js
aem-authoring-toolkit-plugin/src/main/java/com/exadel/aem/toolkit/core/handlers/assets/dependson/DependsOnHandler.java
aem-authoring-toolkit-plugin/src/main/java/com/exadel/aem/toolkit/core/util/DialogConstants.java
aem-authoring-toolkit-plugin/src/test/com/exadel/aem/toolkit/test/dependson/DependsOnRefAnnotation.java
aem-authoring-toolkit-plugin/src/test/resources/dependsOn/dependsOnRef/_cq_dialog.xml

References now observing input event.
"Lazy" references introduced to ignore rapid input event.

[DependsOn]: input event & lazy refs

---

aem-authoring-toolkit-assets/src/main/content/jcr_root/apps/authoring-toolkit/depends-on/README.md
aem-authoring-toolkit-assets/src/main/content/jcr_root/apps/authoring-toolkit/depends-on/js/accessors/dependsOnCoralRTEAccessor.js
aem-authoring-toolkit-assets/src/main/content/jcr_root/apps/authoring-toolkit/depends-on/js/actions/dependsOnFetchAction.js
aem-authoring-toolkit-assets/src/main/content/jcr_root/apps/authoring-toolkit/depends-on/js/dependsOn.js

- small error messages enhancements
- RTE accessors improvements
- plugin runtime version

[DependsOn]: Update 2.4.1

---

aem-authoring-toolkit-plugin/src/main/java/com/exadel/aem/toolkit/core/handlers/assets/dependson/DependsOnHandler.java
aem-authoring-toolkit-plugin/src/test/com/exadel/aem/toolkit/core/maven/DependsOnTest.java
aem-authoring-toolkit-plugin/src/test/com/exadel/aem/toolkit/test/dependson/DependsOnSemicolon.java
aem-authoring-toolkit-plugin/src/test/resources/dependsOn/dependsOnSemicolon/.content.xml
aem-authoring-toolkit-plugin/src/test/resources/dependsOn/dependsOnSemicolon/_cq_dialog.xml
ui.apps/src/main/content/jcr_root/apps/authoring-toolkit/depends-on/README.md
ui.apps/src/main/content/jcr_root/apps/authoring-toolkit/depends-on/js/dependsOnUtils.js

Add ability to escape ';' character via '\;' to be considered as js operator (instead of DependsOn instance separate configuration)

[DependsOn] Support for ';' escaping

---

aem-authoring-toolkit-plugin/src/test/com/exadel/aem/toolkit/test/custom/handler/ordering/DialogManualOrderingTestCases.java
core/src/main/java/com/exadel/aem/toolkit/core/lists/models/ListItem.java
pom.xml
ui.apps/src/main/content/jcr_root/apps/authoring-toolkit/lists/components/content/listItem/.content.xml
ui.apps/src/main/content/jcr_root/apps/authoring-toolkit/lists/components/content/listItem/_cq_editConfig.xml

- fixed issues with list item reordering
- fixed compatibility issue with AEM 6.4
- removed duplicated license

[Tech] AEMBox List bugfixes

---

pom.xml
ui.apps/pom.xml
ui.apps/src/main/content/META-INF/vault/filter.xml

[Tech] Avoid adding redundant files to /apps/authoring-toolkit/install

---

assets/pom.xml
assets/src/main/content/jcr_root/etc/packages/authoring-toolkit/.snapshot/.keep

…ckage, and assets artifact retained in JCR

[Tech] Made sure .snapshot folder is created when preparing assets package, and assets artifact retained in JCR

---

ui.apps/src/main/content/jcr_root/apps/etoolbox-authoring-kit/coral-overlay/.content.xml
ui.apps/src/main/content/jcr_root/apps/etoolbox-authoring-kit/coral-overlay/js/updateValidationSelectors.js
ui.apps/src/main/content/jcr_root/apps/etoolbox-authoring-kit/depends-on/js/actions/dependsOnCoralTabAction.js

https://jira.exadel.com/browse/EDMTP-411

[EDMTP-411] Fixed tab-visibility action to not trigger inner elements

---

core/src/main/java/com/exadel/aem/toolkit/core/lists/models/internal/ListItemModel.java
docs/md/etoolbox-lists.md
ui.apps/src/main/content/jcr_root/apps/etoolbox-authoring-kit/lists/components/content/listItem/clientlibs/dialog/editAction.js
ui.apps/src/main/content/jcr_root/apps/etoolbox-authoring-kit/lists/components/content/listItem/listItem.html

- tune system properties exclusion mechanism
- add the ability to customize info section

[EDMTP-408] List Item enhancements

---

docs/md/depends-on.md
ui.apps/package-lock.json
ui.apps/src/main/content/jcr_root/apps/etoolbox-authoring-kit/depends-on/js/actions/dependsOnCoralBasicActions.js
ui.apps/src/main/content/jcr_root/apps/etoolbox-authoring-kit/depends-on/js/dependsOn.js
ui.apps/src/main/content/jcr_root/apps/etoolbox-authoring-kit/depends-on/js/dependsOnElementAccessors.js

- add debug log method
- move readonly marker update to accessors layer
- documentation fixes

[DependsOn] Small DependsOn cleanup

---

docs/md/option-provider.md

Updated option-provider.md with the provided string literal

[EDMTP-438] Updated option-provider.md

---

plugin/src/main/java/com/exadel/aem/toolkit/plugin/maven/PluginMojo.java
plugin/src/main/java/com/exadel/aem/toolkit/plugin/runtime/ReflectionContextHelper.java
samples/ui.apps/pom.xml

[EAK-307] Fixed XML files being stored several times within one plugin execution

---

plugin/src/main/java/com/exadel/aem/toolkit/plugin/handlers/placement/sections/Section.java
plugin/src/test/com/exadel/aem/toolkit/test/component/ComplexComponent2.java

[EAK-309] Fixed @PlaceOnTab value not honored when distributing widgets across dialog containers

---

core/src/main/java/com/exadel/aem/toolkit/api/annotations/widgets/PathField.java
core/src/main/java/com/exadel/aem/toolkit/api/annotations/widgets/common/NodeFilter.java
docs/content/dev-tools/component-management/dialog-fields/widgets.md
plugin/src/test/com/exadel/aem/toolkit/plugin/maven/WidgetsTest.java
plugin/src/test/com/exadel/aem/toolkit/test/widget/PathFieldWidget.java
plugin/src/test/resources/widget/pathField/.content.xml
plugin/src/test/resources/widget/pathField/_cq_dialog.xml

[EAK-314] Added handling of "droppable" property in @PathField

---

docs/website/src/common/colors.less
docs/website/src/landing/benefits/benefits.less
docs/website/src/landing/business-value/business-value.less
docs/website/views/_includes/landing/business-value.njk

**1. "Stains" with sharp transition** (main option)
- Desktop 
- Mobile 
**2. Big stain with smooth block transition**  (proposal)
- Desktop 
- Mobile 
**3. Simple horizontal gradient** (analog for previous ones)
- Desktop
- Mobile 
[_old designs for reference_](https://user-images.githubusercontent.com/86774452/174602348-bdfce31f-0e79-48a2-91ab-4d89692733eb.png)

[Tech] business value redesign

---

ui.apps/package-lock.json
ui.apps/package.json

[link to this issue](https://github.com/exadel-inc/etoolbox-authoring-kit/issues/331)

[EAK-331] Updated all dependencies in the ui.apps directory

---

docs/website/package-lock.json

due to [failed dependency installation](https://github.com/exadel-inc/etoolbox-authoring-kit/runs/7131164135?check_suite_focus=true#step:4:33) during the GH Pages Build and Deploy

[Tech] Updated dependencies for GH Pages

---

core/src/main/java/com/exadel/aem/toolkit/core/optionprovider/services/impl/HttpOptionSourceResolver.java
core/src/main/java/com/exadel/aem/toolkit/core/optionprovider/services/impl/JcrOptionSourceResolver.java
core/src/main/java/com/exadel/aem/toolkit/core/optionprovider/services/impl/OptionProviderServiceImpl.java
core/src/main/java/com/exadel/aem/toolkit/core/optionprovider/services/impl/OptionSourceResolver.java
core/src/main/java/com/exadel/aem/toolkit/core/optionprovider/servlets/OptionProviderServlet.java
core/src/test/java/com/exadel/aem/toolkit/core/optionprovider/services/impl/OptionProviderTest.java
core/src/test/resources/com/exadel/aem/toolkit/core/optionprovider/httpResponse1.json
core/src/test/resources/com/exadel/aem/toolkit/core/optionprovider/httpResponse2.json
docs/content/dev-tools/option-provider.md

Added methods to OptionProviderServiceImpl that extract Options from the GET request to the URL defined in OptionSource

[EAK-260] Option Provider: consume data from a JSON HTTP response

---

core/src/main/java/com/exadel/aem/toolkit/api/annotations/widgets/slider/Slider.java
core/src/main/java/com/exadel/aem/toolkit/api/annotations/widgets/slider/SliderItem.java
core/src/main/java/com/exadel/aem/toolkit/core/CoreConstants.java
core/src/main/java/com/exadel/aem/toolkit/core/authoring/models/Slider.java
docs/content/dev-tools/component-management/dialog-fields/widgets.md
plugin/src/main/java/com/exadel/aem/toolkit/plugin/handlers/widgets/SliderHandler.java
plugin/src/test/com/exadel/aem/toolkit/test/widget/SliderWidget.java
plugin/src/test/resources/widget/slider/_cq_dialog.xml
ui.apps/src/main/content/jcr_root/apps/etoolbox-authoring-kit/components/authoring/slider/render.html
ui.apps/src/main/content/jcr_root/apps/etoolbox-authoring-kit/coral-overlay/css.txt
ui.apps/src/main/content/jcr_root/apps/etoolbox-authoring-kit/coral-overlay/css/common-styles.css

Created Slider handler for toolkit label items.
Updated documentation and test for slider widget.

[EAK-344] Implemented ranged slider with label items.

---

docs/content/getting-started/installation.md

[Tech] Updated the initial setup manual

[Tech] Updated the initial setup manual

---

core/src/main/java/com/exadel/aem/toolkit/api/annotations/assets/dependson/DependsOnParam.java
core/src/main/java/com/exadel/aem/toolkit/api/annotations/editconfig/DropTargetConfig.java
core/src/main/java/com/exadel/aem/toolkit/api/annotations/editconfig/FormParameter.java
core/src/main/java/com/exadel/aem/toolkit/api/annotations/editconfig/InplaceEditingConfig.java
core/src/main/java/com/exadel/aem/toolkit/api/annotations/editconfig/listener/Listener.java
core/src/main/java/com/exadel/aem/toolkit/api/annotations/layouts/Column.java
core/src/main/java/com/exadel/aem/toolkit/api/annotations/main/ClassMember.java
core/src/main/java/com/exadel/aem/toolkit/api/annotations/widgets/attribute/Data.java
core/src/main/java/com/exadel/aem/toolkit/api/annotations/widgets/autocomplete/AutocompleteDatasource.java
core/src/main/java/com/exadel/aem/toolkit/api/annotations/widgets/autocomplete/AutocompleteList.java
core/src/main/java/com/exadel/aem/toolkit/api/annotations/widgets/autocomplete/AutocompleteTag.java
core/src/main/java/com/exadel/aem/toolkit/api/annotations/widgets/buttongroup/ButtonGroupItem.java
core/src/main/java/com/exadel/aem/toolkit/api/annotations/widgets/common/OptionProvider.java
core/src/main/java/com/exadel/aem/toolkit/api/annotations/widgets/common/OptionSource.java
core/src/main/java/com/exadel/aem/toolkit/api/annotations/widgets/datepicker/DateTimeValue.java
core/src/main/java/com/exadel/aem/toolkit/api/annotations/widgets/radio/RadioButton.java
core/src/main/java/com/exadel/aem/toolkit/api/annotations/widgets/rte/Characters.java
core/src/main/java/com/exadel/aem/toolkit/api/annotations/widgets/rte/HtmlLinkRules.java
core/src/main/java/com/exadel/aem/toolkit/api/annotations/widgets/rte/HtmlPasteRules.java
core/src/main/java/com/exadel/aem/toolkit/api/annotations/widgets/rte/IconMapping.java
core/src/main/java/com/exadel/aem/toolkit/api/annotations/widgets/rte/ParagraphFormat.java
core/src/main/java/com/exadel/aem/toolkit/api/annotations/widgets/rte/Style.java
core/src/main/java/com/exadel/aem/toolkit/api/annotations/widgets/select/Option.java

[EAK-414] Added @Target({}) for those annotations that should be used only as properties' value of other annotations.

[EAK-414] Added @Target({}) for those annotations that should be used only as properties' value of other annotations

---

docs/content/dev-tools/depends-on/api.md
ui.apps/src/main/content/jcr_root/apps/etoolbox-authoring-kit/depends-on/js.txt
ui.apps/src/main/content/jcr_root/apps/etoolbox-authoring-kit/depends-on/js/accessors/dependsOnCoral2AutocompleteAccessor.js
ui.apps/src/main/content/jcr_root/apps/etoolbox-authoring-kit/depends-on/js/accessors/dependsOnCoralFieldsetAccessor.js
ui.apps/src/main/content/jcr_root/apps/etoolbox-authoring-kit/depends-on/js/actions/dependsOnCoralBasicActions.js
ui.apps/src/main/content/jcr_root/apps/etoolbox-authoring-kit/depends-on/js/dependsOn.js
ui.apps/src/main/content/jcr_root/apps/etoolbox-authoring-kit/depends-on/js/dependsOnElementAccessors.js

DependsOn plugin updated with extended support of disable action (internal and external), support fot disable action for fieldset and support for Coral2 Autocomplete widget.
Closes: #455
Closes: #456
Closes: #429

[EAK-429, EAK-456, EAK-455]: DependsOn plugin update (2.7.0)

---

docs/content/dev-tools/depends-on/api.md
ui.apps/src/main/content/jcr_root/apps/etoolbox-authoring-kit/depends-on/js.txt
ui.apps/src/main/content/jcr_root/apps/etoolbox-authoring-kit/depends-on/js/accessors/dependsOnCoral2AutocompleteAccessor.js
ui.apps/src/main/content/jcr_root/apps/etoolbox-authoring-kit/depends-on/js/accessors/dependsOnCoralFieldsetAccessor.js
ui.apps/src/main/content/jcr_root/apps/etoolbox-authoring-kit/depends-on/js/actions/dependsOnCoralBasicActions.js
ui.apps/src/main/content/jcr_root/apps/etoolbox-authoring-kit/depends-on/js/dependsOn.js
ui.apps/src/main/content/jcr_root/apps/etoolbox-authoring-kit/depends-on/js/dependsOnElementAccessors.js

Copy of #461 to `develop` branch

[EAK-429, EAK-456, EAK-455] DependsOn plugin update (2.7.0) (copy of #461)

---

docs/website/.eleventy.js
docs/website/11ty/open.postaction.js
docs/website/package-lock.json
docs/website/package.json
ui.apps/package-lock.json
ui.apps/package.json

[Bump docs/website dependencies](https://github.com/exadel-inc/etoolbox-authoring-kit/commit/9a456dc8d4ddb9752697e6ece87bb7cae7550833)
[Update 11ty to the 2.0.1 version](https://github.com/exadel-inc/etoolbox-authoring-kit/commit/af5ac1726900ee5271f37da452bc798e23bd223e)
[Bump ui.apps eslint](https://github.com/exadel-inc/etoolbox-authoring-kit/commit/9031cf1eb3510693085b0ac126ff6ada9e7d4f15)

[EAK-460] Bump npm dependencies for site and linting

---

docs/website/.stylelintrc.yml
docs/website/11ty/markdown.shortcut.js
docs/website/11ty/slice.filter.js
docs/website/11ty/sort.filter.js
docs/website/src/common/helpers.less
docs/website/src/common/markdown.less
docs/website/src/common/reboot.less
docs/website/src/common/typography.less
docs/website/src/landing/article-section/article-section.less
docs/website/src/landing/banner/banner.less
docs/website/src/landing/business-value/business-value.less
docs/website/src/navigation/footer/footer.less
docs/website/src/navigation/sidebar/sidebar-content.less
docs/website/views/_includes/landing/article-section.njk
docs/website/views/_layouts/base.njk
docs/website/webpack.config.js

[Remove unnecessary target webpack property](https://github.com/exadel-inc/etoolbox-authoring-kit/commit/d2cd76f94d018fd7b99deef15f58820732dde386)
[Additional stylelint rules](https://github.com/exadel-inc/etoolbox-authoring-kit/commit/de467a47fb7b08220ea56f4f99718176183729c9)
[Template refactoring](https://github.com/exadel-inc/etoolbox-authoring-kit/commit/6245a226e007267af8846c1c8ed3b5a5339ad2b2)

[EAK-460] `docs/website` template updates

---

ui.apps/src/main/content/jcr_root/apps/etoolbox-authoring-kit/config/.content.xml
ui.apps/src/main/content/jcr_root/apps/etoolbox-authoring-kit/config/org.apache.sling.commons.log.LogManager.factory.config-eak.xml

[EAK-422] Created a dedicated log configuration

---

core/src/main/java/com/exadel/aem/toolkit/api/annotations/editconfig/DropTargetConfig.java
plugin/src/main/java/com/exadel/aem/toolkit/plugin/handlers/editconfig/DropTargetsHandler.java
plugin/src/test/com/exadel/aem/toolkit/plugin/validators/ValidatorsTest.java
plugin/src/test/com/exadel/aem/toolkit/plugin/validators/cases/ValidatorTestCases.java

[EAK-503] Imposed value restrictions on @DropTargetConfig properties

---

docs/content/getting-started/installation.md
plugin/src/main/java/com/exadel/aem/toolkit/plugin/runtime/ReflectionContextHelper.java

[EAK-513] Added the ability to specify comma-separated componentsReferenceBase values

---

docs/content/dev-tools/component-management/dialog-fields/configuring-multifield.md
plugin/src/main/java/com/exadel/aem/toolkit/plugin/handlers/widgets/common/DialogFieldAnnotationHandler.java
plugin/src/test/com/exadel/aem/toolkit/plugin/handlers/widgets/cases/FieldSetWidget.java
plugin/src/test/resources/handlers/widgets/fieldSet/_cq_dialog.xml

[EAK-523] Disabled prepending prefixes to field names in composite multifields

---

core/src/main/java/com/exadel/aem/toolkit/api/annotations/meta/StringTransformation.java
core/src/test/java/com/exadel/aem/toolkit/AllTests.java
core/src/test/java/com/exadel/aem/toolkit/api/annotations/meta/StringTransformationTest.java

[EAK-527] Enhance the string transformation routine

---

it.tests/src/test/java/com/exadel/aem/toolkit/it/cases/allowedchildren/ContainerComponent1.java
it.tests/src/test/java/com/exadel/aem/toolkit/it/cases/allowedchildren/VideoChildMixin.java
plugin/src/main/java/com/exadel/aem/toolkit/plugin/handlers/common/AllowedChildrenHandler.java
plugin/src/main/java/com/exadel/aem/toolkit/plugin/sources/ComponentSource.java
plugin/src/main/java/com/exadel/aem/toolkit/plugin/sources/ComponentSourceImpl.java
plugin/src/main/java/com/exadel/aem/toolkit/plugin/utils/ArrayUtil.java
plugin/src/main/java/com/exadel/aem/toolkit/plugin/writers/PackageWriter.java
plugin/src/test/com/exadel/aem/toolkit/plugin/handlers/common/AllowedChildrenTest.java
plugin/src/test/com/exadel/aem/toolkit/plugin/handlers/common/cases/policies/AllowedChildrenTestCases.java
plugin/src/test/resources/handlers/common/policies/allowedChildren/withViews/.content.xml
plugin/src/test/resources/handlers/common/policies/allowedChildren/withViews/_cq_editConfig.xml

[EAK-502] Ability to combine @AllowedChildren from different entries of a "view model" group

---

plugin/src/main/java/com/exadel/aem/toolkit/plugin/maven/PluginMojo.java

[EAK-540] Handled the configuration-less plugin setup

---

plugin/src/main/java/com/exadel/aem/toolkit/plugin/maven/PluginMojo.java
plugin/src/main/java/com/exadel/aem/toolkit/plugin/maven/PluginSettings.java

[EAK-542] Added support for the config properties specified in <execution> sections

---

ui.apps/src/main/content/jcr_root/apps/etoolbox-authoring-kit/depends-on/js/dependsOnQueryObserver.js

[EAK-561] Depends On: action unhandled exceptions could break initialization flow

---

core/pom.xml
core/src/main/java/com/exadel/aem/toolkit/core/CoreConstants.java
core/src/main/java/com/exadel/aem/toolkit/core/lists/servlets/ListsJsonServlet.java
core/src/main/java/com/exadel/aem/toolkit/core/lists/servlets/ListsServlet.java
core/src/main/java/com/exadel/aem/toolkit/core/optionprovider/servlets/OptionProviderServlet.java
core/src/test/java/com/exadel/aem/toolkit/core/lists/servlets/ListsJsonServletTest.java
docs/content/authoring-tools/etoolbox-lists.md
pom.xml

[EAK-558] Support for outputting EToolbox Lists in JSON

---

core/src/main/java/com/exadel/aem/toolkit/api/annotations/widgets/rte/HtmlLinkRules.java
core/src/main/java/com/exadel/aem/toolkit/api/annotations/widgets/rte/LinkTarget.java
plugin/src/test/com/exadel/aem/toolkit/plugin/handlers/common/cases/components/ScriptedComponent.java
plugin/src/test/com/exadel/aem/toolkit/plugin/handlers/widgets/cases/RichTextEditorWidget.java
plugin/src/test/resources/handlers/common/components/generic/scriptedComponent/_cq_dialog.xml
plugin/src/test/resources/handlers/widgets/richTextEditor/_cq_dialog.xml

[EAK-566] Changed the structure of LinkTarget options

---

docs/content/dev-tools/component-management/customizing-toolkit.md
pom.xml

[Tech] Updated Jackson dependency version

---

.github/workflows/cla.yml
.github/workflows/tests.yml
ui.apps/eslint.config.mjs
ui.apps/jest.config.js
ui.apps/jest/clientlib.transform.js
ui.apps/jest/granite.mocks.js
ui.apps/jest/granite.setup.js
ui.apps/package-lock.json
ui.apps/package.json
ui.apps/pom.xml
ui.apps/src/main/content/META-INF/vault/filter.xml
ui.apps/src/main/content/jcr_root/apps/etoolbox-authoring-kit/depends-on/js/dependsOn.js
ui.apps/src/main/content/jcr_root/apps/etoolbox-authoring-kit/depends-on/js/dependsOnElementAccessors.js
ui.apps/src/main/content/jcr_root/apps/etoolbox-authoring-kit/depends-on/tests/dependsOnElementAccessors.test.js

- Managed requests support
- CI: bump and update versions for CI actions
- UI Unit tests bootstrap + 1 wave of actual tests

[EAK-572] DependsOn: support for managed actions for require, visibility and readonly

---

plugin/src/main/java/com/exadel/aem/toolkit/plugin/maven/PluginMojo.java
pom.xml

[EAK-580] Fixed the "parameter is read-only" warning while building in AEMaaCS

---

plugin/src/main/java/com/exadel/aem/toolkit/plugin/handlers/dependson/DependsOnTabHandler.java
plugin/src/test/com/exadel/aem/toolkit/plugin/handlers/dependson/cases/DependsOnTabAnnotation.java
plugin/src/test/com/exadel/aem/toolkit/plugin/maven/TestConstants.java
plugin/src/test/resources/handlers/common/components/generic/complexComponent2/_cq_dialog.xml
plugin/src/test/resources/handlers/dependsOn/dependsOnTab/_cq_dialog.xml

[EAK-584] Fixed NPE when handling a tab with a non-conventional symbol in title

---

ui.apps/src/main/content/jcr_root/apps/etoolbox-authoring-kit/depends-on/js/actions/dependsOnCoralTabAction.js
ui.apps/src/main/content/jcr_root/apps/etoolbox-authoring-kit/depends-on/js/dependsOn.js
ui.apps/src/main/content/jcr_root/apps/etoolbox-authoring-kit/depends-on/js/dependsOnQueryObserver.js

[EAK-594] DependsOn: fix DependsOnTab to respect subfields own conditional visibility (missing actor for setVisibility request on subfields)
